<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1bulbasaur</name>
   <tag></tag>
   <elementGuidId>3369f275-bcc2-44c1-8bf6-91a9b19da95e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card__container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7cd40429-91a8-43f0-b4f9-84dbe0a9c5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__container</value>
      <webElementGuid>0448de9f-53be-4ad6-84b3-80b2a4fa1139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1bulbasaur</value>
      <webElementGuid>9d3d11e6-3164-4274-add1-800d9817090f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;container&quot;]/div[@class=&quot;card__info&quot;]/div[@class=&quot;card__container&quot;]</value>
      <webElementGuid>c0d3e45d-8dc4-498c-881a-75e84cc9eb81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div</value>
      <webElementGuid>d29dd8f8-bb88-46e1-86e0-c28661f077bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemons'])[1]/following::div[2]</value>
      <webElementGuid>b935a30d-7d64-41f9-800a-5f4f981fe81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ivysaur'])[1]/preceding::div[1]</value>
      <webElementGuid>29ca1899-b294-48da-92a2-40a5d3b0b527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>a00a2171-90c5-4cd9-82fe-fafbc6b43c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1bulbasaur' or . = '1bulbasaur')]</value>
      <webElementGuid>3ac37653-5c4a-4fac-be03-377b7e155f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
