<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_overgrow</name>
   <tag></tag>
   <elementGuidId>9bbca83d-ca2c-4dd6-b39e-ba6c1b387c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af3ad074-0acd-4dfa-8cbf-394e5b047060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>7ed77aa7-cb55-48a6-8732-b7d725642e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>overgrow</value>
      <webElementGuid>623c7e93-dac8-4f81-a138-a458dd75ea59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/div[@class=&quot;abilities&quot;]/div[@class=&quot;group&quot;]</value>
      <webElementGuid>288b3b47-77ab-4c07-bcf1-b4c6a7e1f4d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/div/div</value>
      <webElementGuid>767a31aa-70d6-419d-86cc-b52b1e905386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bulbasaur'])[2]/following::div[2]</value>
      <webElementGuid>6746ca55-a066-4da8-ad9b-d31a6320b0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::div[3]</value>
      <webElementGuid>a7fade5e-caea-478c-9474-2fbce2d37802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chlorophyll'])[1]/preceding::div[1]</value>
      <webElementGuid>fefa42b5-0e81-4600-938d-56511b140277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>f5f9474b-6f97-49c1-b78c-6bc95a75aa10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'overgrow' or . = 'overgrow')]</value>
      <webElementGuid>11b4f69c-84f2-4056-a73a-06e22ea384d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
