<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Pokemons</name>
   <tag></tag>
   <elementGuidId>944668c7-8142-4a08-97e6-218d2e970088</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>62431550-9032-4942-aeb5-37fadab94814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>10b138a6-640c-4213-9f7e-e19314f7d3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pokemons</value>
      <webElementGuid>8dd544fa-9b35-4ba3-9c5c-e9abd5a08f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;container&quot;]/h1[@class=&quot;title&quot;]</value>
      <webElementGuid>2867daf8-5806-4666-b907-a4d2b8aa3ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/h1</value>
      <webElementGuid>7708004f-50b0-4998-bd78-b143ba9cdfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bulbasaur'])[1]/preceding::h1[1]</value>
      <webElementGuid>b351345a-5599-4708-bd91-5a4fb8913587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ivysaur'])[1]/preceding::h1[1]</value>
      <webElementGuid>d3a0c956-8107-452c-ad4e-45f608b34d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pokemons']/parent::*</value>
      <webElementGuid>6673df6d-ad28-4f5f-904b-f11a6258bbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ad39b9f8-f3a3-4485-bdf6-aee4bea6c721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Pokemons' or . = 'Pokemons')]</value>
      <webElementGuid>8bcf542c-b437-413f-b640-81cc808deea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
