<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_kakuna</name>
   <tag></tag>
   <elementGuidId>5886598b-69cf-4384-8545-b73fd385cc4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.names</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>0ebf2289-ed6c-4c77-8bc9-364b5b17f877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>names</value>
      <webElementGuid>d49596c8-2067-4b9f-8b67-759bf6d637c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kakuna</value>
      <webElementGuid>a4da969c-26dd-4429-bcf0-ae5e0caad46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/h2[@class=&quot;names&quot;]</value>
      <webElementGuid>811fc82a-4416-4a55-8562-24152de5b5a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/h2</value>
      <webElementGuid>c1f365f8-07db-4987-9514-ab56cd0a9f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::h2[1]</value>
      <webElementGuid>5bc58090-dfce-4aa7-8aa4-752f63ef2b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raticate'])[1]/following::h2[1]</value>
      <webElementGuid>2d5fa84b-071c-4970-bd0c-4a519e3b5e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shed-skin'])[1]/preceding::h2[1]</value>
      <webElementGuid>6fd021d8-426f-46dc-b093-455189337efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h2</value>
      <webElementGuid>31c1a212-d403-4fec-a4be-04488b17ba41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'kakuna' or . = 'kakuna')]</value>
      <webElementGuid>3f130fa6-1e32-4880-a0b4-6866bec9fe76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
