<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_shed-skin</name>
   <tag></tag>
   <elementGuidId>b48df15f-8fcb-4deb-aee9-155faa247aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.group > h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>49904224-534a-45e2-8bd2-f1bac8af317a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shed-skin</value>
      <webElementGuid>77d0b97a-a343-4ccc-be00-1340126f2ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/div[@class=&quot;abilities&quot;]/div[@class=&quot;group&quot;]/h2[1]</value>
      <webElementGuid>5bc5a11c-d5c4-40dd-8855-580bbf3b020a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/div/div/h2</value>
      <webElementGuid>7e017dec-5406-4268-8426-845f2a300a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kakuna'])[2]/following::h2[1]</value>
      <webElementGuid>cf0a327e-5b7b-4147-9c47-94aee370d9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::h2[2]</value>
      <webElementGuid>075beb09-2138-43d0-b100-4bc43491e5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='shed-skin']/parent::*</value>
      <webElementGuid>5514b6c3-075d-40c5-97ef-eb08b2c89458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/h2</value>
      <webElementGuid>74addb1f-3a50-4f13-b854-7e35e19b06ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'shed-skin' or . = 'shed-skin')]</value>
      <webElementGuid>ee608ba6-a27b-4b13-b63b-067b62324eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
