<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_attack  25</name>
   <tag></tag>
   <elementGuidId>0f1ff162-3562-40cf-a1a1-b6e8ebc34119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/div[2]/h3[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>7b1b70d4-de20-48cb-8c7f-6d1e4f408ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> attack : 25 </value>
      <webElementGuid>6ee81818-5dae-47d1-97e6-ecebed37c36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/div[@class=&quot;content&quot;]/h3[2]</value>
      <webElementGuid>e01dd8a1-b2e0-42a3-9ceb-04c30dbaa8fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/div[2]/h3[2]</value>
      <webElementGuid>f20af3d4-08ac-47c2-8cdf-380bd91e6514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shed-skin'])[1]/following::h3[2]</value>
      <webElementGuid>ff427cc3-dee4-4330-88fb-86493eaad1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='attack']/parent::*</value>
      <webElementGuid>ee5d16d7-4599-4967-be9f-6341220f8cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3[2]</value>
      <webElementGuid>6ba2f41f-85b7-4ebd-90e8-6607000d0c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = ' attack : 25 ' or . = ' attack : 25 ')]</value>
      <webElementGuid>df84bfb3-3d1a-4090-bfb5-c908afe5bf6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
