<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bulbasaur_img</name>
   <tag></tag>
   <elementGuidId>c5f96d76-521d-438e-bc72-22156d5e4957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>512207bc-4ed9-4ab5-bce3-5e7b0e74a44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg</value>
      <webElementGuid>c56e7f57-822e-49b1-82c6-339fa996e67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pokemon__img</value>
      <webElementGuid>ea4be520-c49b-4ec6-8b87-6f99b4178b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8559803c-9dfb-42cd-afe5-00c616113473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/img[@class=&quot;img&quot;]</value>
      <webElementGuid>6bfadfec-ccfd-42d3-a79e-9ebdc45800e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/img</value>
      <webElementGuid>6cb9f264-63fb-4d4b-8fe8-f4104c83a0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='pokemon__img']</value>
      <webElementGuid>85fd3f34-63c5-458a-9f54-ffe4f44e5dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>0ebce024-97fe-4939-a0ff-a568dfc17993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg' and @alt = 'pokemon__img']</value>
      <webElementGuid>c8486ad1-58fd-40d4-8567-8888902d2519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
