<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Peso85Habilidadesblazesolar-powerTiposf_d07889</name>
   <tag></tag>
   <elementGuidId>4327dde9-4d2c-45d2-84a5-76b8213b8742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07f9f839-60f3-4431-ba53-f0df86bb572f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>e15df117-955f-4422-8056-07c8a52f4f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Peso85Habilidades:blazesolar-powerTiposfireJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2</value>
      <webElementGuid>80ff5e29-01eb-4f58-aa3d-8919201ecf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]</value>
      <webElementGuid>dcedd5e6-49bc-4152-89f5-8f44e0e86397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]</value>
      <webElementGuid>d867be70-ae30-458c-9150-7a81073ddca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='charmander'])[1]/following::div[1]</value>
      <webElementGuid>0ec00a77-feaf-4fe9-a829-3cce65161b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Busca a tu Pokemon'])[1]/following::div[4]</value>
      <webElementGuid>a4fe02d8-cf0e-4d26-819b-c36e2d15c526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>5a7f5c0e-b09e-41d3-9abf-c7a37226f48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Peso85Habilidades:blazesolar-powerTiposfireJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2' or . = 'Peso85Habilidades:blazesolar-powerTiposfireJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2')]</value>
      <webElementGuid>8095fb59-ff41-48f4-a214-c17ee6f3c8f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
