<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_charmeleon</name>
   <tag></tag>
   <elementGuidId>bda3b93a-fadc-458c-b48c-2cdddbd0e3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card > h2.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>bb70bd5e-7ac3-4a5f-99de-f839d99d414d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>5895ab1d-0095-4415-aea4-a7cf8db6208c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>charmeleon</value>
      <webElementGuid>9f9ba4f8-8b2e-43fb-ae6a-e0419c7b7582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]/h2[@class=&quot;title&quot;]</value>
      <webElementGuid>d4ab8b5d-0a6f-4c01-bb53-b748bcfaee28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/h2</value>
      <webElementGuid>787a8fb7-d822-4980-956a-d86865cc42f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Busca a tu Pokemon'])[1]/following::h2[1]</value>
      <webElementGuid>a9f8cbad-1bd7-4221-9803-0baa064f5346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos'])[1]/following::h2[2]</value>
      <webElementGuid>913fbbd2-2d41-4b7d-b550-fe4daf7a85af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/preceding::h2[1]</value>
      <webElementGuid>49a48af2-c81c-421c-86aa-6e155c823a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilidades:'])[1]/preceding::h2[1]</value>
      <webElementGuid>25c515fd-de35-4948-b07f-40c02e45d7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='charmeleon']/parent::*</value>
      <webElementGuid>38323cc0-728b-4cfa-9765-e6af10fd3815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/h2</value>
      <webElementGuid>27e2398f-d488-40d4-883d-34578f16da37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'charmeleon' or . = 'charmeleon')]</value>
      <webElementGuid>d7ea3ca1-4910-4223-b1f4-732e356d5398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
