<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Busca a tu Pokemon_search-bar</name>
   <tag></tag>
   <elementGuidId>855936b0-a80d-4145-bf74-48f1569be42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.search-bar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec3eac69-7425-443e-8b1b-edfe71aca34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-bar</value>
      <webElementGuid>cc72f9f9-54cb-47df-8db5-908ead7486aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>143dbe4c-787a-4573-a166-88db13d8b932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Introduce el nombre de tu pokemon</value>
      <webElementGuid>3247d215-0a34-4e59-b21d-614dcd203aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/form[1]/input[@class=&quot;search-bar&quot;]</value>
      <webElementGuid>32b71860-d9ad-4402-a331-b36c7e2ce21b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>505b3f84-8088-405d-a2ff-769c07585097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/input</value>
      <webElementGuid>3fc18597-c89b-4b0b-b1ed-711a6ae54335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>26ab28e5-f252-4129-9dcd-9be5d5752604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Introduce el nombre de tu pokemon']</value>
      <webElementGuid>d28f57e9-2c89-476e-af60-677091fe747a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
