<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_platinum</name>
   <tag></tag>
   <elementGuidId>4545dc8b-c3ec-4d3e-82b7-629478940bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[3]/p[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c4c9ba9f-5239-4381-8890-c239d8818eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-item</value>
      <webElementGuid>32e92434-d1ed-445c-87d4-3dec23cf4f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>platinum</value>
      <webElementGuid>d435828a-5a6e-4317-a5c3-55a34243cd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;container&quot;]/p[@class=&quot;card-item&quot;]</value>
      <webElementGuid>de39eaf8-842d-403e-9e57-4d41b22118c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/p[14]</value>
      <webElementGuid>4670b7b4-ffd3-4e97-8559-d9d023214e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Juegos en los que aparece'])[1]/following::p[14]</value>
      <webElementGuid>a2005074-5345-4b85-9ed2-dc105b6383e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos'])[1]/following::p[15]</value>
      <webElementGuid>b47e96b9-a876-46ea-b7d1-4650c5a81af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='platinum']/parent::*</value>
      <webElementGuid>a360624d-15c7-4d78-9104-40c1cf389ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[14]</value>
      <webElementGuid>e81eeafb-ea21-4f7d-9f36-e7ad14daae20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'platinum' or . = 'platinum')]</value>
      <webElementGuid>f650633a-6bd7-47aa-bca2-9ecb62e3a461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
