<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next page</name>
   <tag></tag>
   <elementGuidId>165ba229-1c34-4677-b5d0-0dabb017f654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.botones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22d2289b-3af6-4fd8-ae2b-ad586a4711c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botones</value>
      <webElementGuid>e445cf3e-e5c3-4b74-85f2-63b13aae2bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next page</value>
      <webElementGuid>602051d5-c72c-4325-9ee3-8ace9bf5eac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;center&quot;]/button[@class=&quot;botones&quot;]</value>
      <webElementGuid>51c1abaf-2001-4bcc-abec-1fddb738f1b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/button</value>
      <webElementGuid>555b3f4d-78e3-45b5-ab5e-1566f61fc237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemons list'])[1]/following::button[1]</value>
      <webElementGuid>9012c3c8-5984-417a-8efb-a600b6d14ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/following::button[1]</value>
      <webElementGuid>69dbce6f-026c-47f0-b186-c8894552c0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bulbasaur'])[1]/preceding::button[1]</value>
      <webElementGuid>284cdb36-e13f-4cb3-a4cd-347d7d8037e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilidades:'])[1]/preceding::button[1]</value>
      <webElementGuid>3d816cec-d1a8-44cf-9383-4c4b49bace0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next page']/parent::*</value>
      <webElementGuid>6cd4b81b-fc3b-4ff1-89cb-9f234999ae7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0c5b7228-1a4a-4df3-bc25-1e32ca5667e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next page' or . = 'Next page')]</value>
      <webElementGuid>aaf74d84-58e2-4f84-ae04-53c70abdb30d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
