<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_rain-dish</name>
   <tag></tag>
   <elementGuidId>53464eca-14d4-46e7-a00f-1cd8b4a69336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/div/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5224da63-1991-4627-ac74-9a13b5c3e6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rain-dish</value>
      <webElementGuid>8ab974af-dc9f-4ae1-a070-e8015eda91c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/div[@class=&quot;abilities&quot;]/div[@class=&quot;group&quot;]/h2[1]</value>
      <webElementGuid>3248063b-07d5-4f2e-bb04-a07290e6cafc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/div/div[2]/h2</value>
      <webElementGuid>0404766c-cce2-4780-ad6b-ab4fa6183465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='torrent'])[1]/following::h2[1]</value>
      <webElementGuid>652bbfea-c10e-4b83-ba9d-22ef89f01a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wartortle'])[2]/following::h2[2]</value>
      <webElementGuid>06a8e005-87f9-429f-9a6f-da21008fa50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='rain-dish']/parent::*</value>
      <webElementGuid>9fb2e0f3-2ffc-45fd-bf5c-9c7b962601d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/h2</value>
      <webElementGuid>f5bb2223-fefb-4939-8ee1-09b07522382d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'rain-dish' or . = 'rain-dish')]</value>
      <webElementGuid>b93d2202-f3bb-4555-a635-31f0dd2b5ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
