<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_wartortle</name>
   <tag></tag>
   <elementGuidId>63d37f90-2c9f-43b6-a65c-9c2ae7f9e14c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.names</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>9a5c32ae-2552-4ba0-8fc4-90529a435018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>names</value>
      <webElementGuid>ae8fc2f5-fb6a-491a-882c-d93fd4fd1297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>wartortle</value>
      <webElementGuid>c715c8dc-c3b8-4dbf-aa4c-46498600caaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/h2[@class=&quot;names&quot;]</value>
      <webElementGuid>4c3b9eea-11c5-4cb7-a17c-341c4bb9304d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/h2</value>
      <webElementGuid>c91d1444-76b5-4cd1-b68f-871793fe401b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::h2[1]</value>
      <webElementGuid>a3a6e627-9c2c-439e-a561-3ef5be029388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raticate'])[1]/following::h2[1]</value>
      <webElementGuid>92919c69-6776-4c04-9332-f76b8ffc290b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='torrent'])[1]/preceding::h2[1]</value>
      <webElementGuid>f64e49a1-0068-4eb8-aea4-8dd21b544fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rain-dish'])[1]/preceding::h2[2]</value>
      <webElementGuid>f1a5380b-20bf-4a81-b3de-494284d6aed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h2</value>
      <webElementGuid>19f882b2-2a09-4883-86b6-abcc9b437f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'wartortle' or . = 'wartortle')]</value>
      <webElementGuid>b301abda-41a5-442d-a6df-c77c16d992ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
