<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Xpidgeottokeen-eyetangled-feetbig-pecks_761c4c</name>
   <tag></tag>
   <elementGuidId>7e0c4d14-c941-4a3f-9fe5-405542ff8b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a35359ce-d79c-47d0-987b-2704d5245745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__showText</value>
      <webElementGuid>d6c36c3d-8895-46ee-a2d2-5b80bf9044eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show1</value>
      <webElementGuid>3003a690-26af-4cad-b2f9-149aa6b539cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xpidgeottokeen-eyetangled-feetbig-pecks hp : 63  attack : 60  defense : 55  special-attack : 50  special-defense : 50  speed : 71 </value>
      <webElementGuid>71faa906-cc4b-4304-8efd-72095c0bf6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)</value>
      <webElementGuid>01002381-6097-4585-b13c-bce24f46abdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='show1']</value>
      <webElementGuid>c1792ed1-6f01-478d-a650-e9ae3ecd0875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>58a8ba5e-25b9-4e79-938b-3a02649551b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raticate'])[1]/following::div[1]</value>
      <webElementGuid>e40a9077-c349-4fdf-9638-cfade99e8677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rattata'])[1]/following::div[2]</value>
      <webElementGuid>fd44bfeb-df2d-432f-b7e6-efb42180ba8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>4dcb6a03-9aea-4a4d-a45c-8546d1f1ff68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'show1' and (text() = 'Xpidgeottokeen-eyetangled-feetbig-pecks hp : 63  attack : 60  defense : 55  special-attack : 50  special-defense : 50  speed : 71 ' or . = 'Xpidgeottokeen-eyetangled-feetbig-pecks hp : 63  attack : 60  defense : 55  special-attack : 50  special-defense : 50  speed : 71 ')]</value>
      <webElementGuid>a94f05d4-1a01-485c-ad3c-f84565f09ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
