<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_pidgeotto_img</name>
   <tag></tag>
   <elementGuidId>a4f0272f-024d-48ae-b471-7fba6fc79c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35b14efc-aa3a-4c22-9860-f5140cb7c731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/17.svg</value>
      <webElementGuid>fa9367cb-21e3-4c22-adf8-5f180735eb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pokemon__img</value>
      <webElementGuid>def71fac-daa6-466d-bb84-1d35d57e6479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b9b03c3d-510b-4412-83b5-facc8d2c59f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/img[@class=&quot;img&quot;]</value>
      <webElementGuid>0d527dec-ad77-4926-acca-bd943c93a0a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/img</value>
      <webElementGuid>09cbfaf3-e150-4644-af2a-985a1ba1b2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='pokemon__img']</value>
      <webElementGuid>7d69d7f3-e383-4e58-b5f5-a910f200ae22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>bafa13bb-98ed-476f-9108-670e5b99414f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/17.svg' and @alt = 'pokemon__img']</value>
      <webElementGuid>6580d8b9-96fe-4ca0-9ca1-c36a6d339fcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
