<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_pidgey_img</name>
   <tag></tag>
   <elementGuidId>6bc8a97b-5329-4634-b139-1fd0a672d0c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3e03b442-7e80-4c28-ba0c-1995a47c2f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/16.svg</value>
      <webElementGuid>a48e8568-bffd-4d3a-ba46-9d3cb24a0aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pokemon__img</value>
      <webElementGuid>04d60653-b146-4baf-8a18-9525471e5c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a02e0c5a-a743-437a-84a7-fbf34c1f7768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/img[@class=&quot;img&quot;]</value>
      <webElementGuid>6bf9bc00-1102-406e-b0d7-cb88ee8a1889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/img</value>
      <webElementGuid>e07e4cd4-5d27-43ac-9153-1871764ed857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='pokemon__img']</value>
      <webElementGuid>1110fa08-845c-4f5a-b04c-716c68964181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>a8e015a8-08b9-44ad-a443-9057656746fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/16.svg' and @alt = 'pokemon__img']</value>
      <webElementGuid>382779bc-0a0d-4cd9-ba63-dad8469fb2f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
