<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ver listado</name>
   <tag></tag>
   <elementGuidId>386484c4-207f-479a-b376-fe987d9529ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13d253a4-aa3f-48d5-9581-633be62ea48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>a49bf648-3abf-4f76-b8a4-cc7faa8ab379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/todos-los-pokemon</value>
      <webElementGuid>bc9a990c-2bd4-4dc3-b50f-70fefcbcdb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver listado!</value>
      <webElementGuid>5e06711b-aecd-4ea6-9ed6-8cb42945fb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container2&quot;]/a[@class=&quot;btn&quot;]</value>
      <webElementGuid>94af4fed-5d05-413a-857d-82dae1baf703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/a</value>
      <webElementGuid>9e1f57b3-0f3b-426b-9ca7-13bc1a89404a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ver listado!')]</value>
      <webElementGuid>0de85658-b08b-4317-b9d3-80ac6508375a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokepedia'])[1]/following::a[1]</value>
      <webElementGuid>b44cadee-8bc8-4435-a1b8-3759a585a2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos'])[1]/following::a[1]</value>
      <webElementGuid>e954215f-ff0d-427e-9610-6e28c54c1202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar!'])[1]/preceding::a[1]</value>
      <webElementGuid>d3d90337-a06d-48c5-baa2-ae106e721dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver listado!']/parent::*</value>
      <webElementGuid>818d0f38-796d-4d75-8454-7a239a54aca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/todos-los-pokemon')])[2]</value>
      <webElementGuid>46fda7c2-623f-4b06-8140-067c014ee9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>15e8a08f-83e6-4f04-a186-36cbcfd60d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/todos-los-pokemon' and (text() = 'Ver listado!' or . = 'Ver listado!')]</value>
      <webElementGuid>c050ac63-26a2-403c-a2e2-909bf2319e95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
