<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ID 1</name>
   <tag></tag>
   <elementGuidId>eb325b2a-c92f-4591-b237-9ff887cc3cc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>17447113-5519-4702-a448-b9fc036640e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>5258f1d5-3762-48d3-a8a5-f21d11a352db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID: 1 </value>
      <webElementGuid>dbb56a47-a362-4c2c-ab40-fbc767fda23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/table[1]/tbody[@class=&quot;container&quot;]/tr[@class=&quot;card2&quot;]/td[@class=&quot;container&quot;]</value>
      <webElementGuid>06a72eff-1df3-4b1f-9c07-98b40ef66d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/table/tbody/tr/td</value>
      <webElementGuid>eef4d15f-4bf4-4781-b94e-c34a3acc9870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='siguiente'])[1]/following::td[1]</value>
      <webElementGuid>f3571be3-e2db-4fec-815b-cd139c995cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aca podras encontrar un listado con todos los pokemons'])[1]/following::td[1]</value>
      <webElementGuid>72ac27f1-637a-4f86-bcea-ac53dabba10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ID:']/parent::*</value>
      <webElementGuid>a4bbb371-b8b9-410e-a5ad-e33f1da0dcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>3475ebf8-1f8c-421f-8d41-9486b663e75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'ID: 1 ' or . = 'ID: 1 ')]</value>
      <webElementGuid>8073776c-ccb2-46dd-aa52-063748f72691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
