<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 Bulbasaur 6.9 kg0.7 mPesoAltura</name>
   <tag></tag>
   <elementGuidId>ebc5c331-ba5d-4088-893b-a651e52ae710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0cb07cb-3311-4468-a48d-1108fc5b7cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__items</value>
      <webElementGuid>4f683aeb-d6c3-40c3-a8c7-c2bfccecd8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Bulbasaur 6.9 kg0.7 mPesoAltura</value>
      <webElementGuid>213964b2-1e89-4c05-aae0-d002f7dc746d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]</value>
      <webElementGuid>d6a0b4fb-4b46-4b22-b504-78c4813a2741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]</value>
      <webElementGuid>be7eea44-1e16-4f33-a535-5d6497872278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilidades'])[1]/following::div[1]</value>
      <webElementGuid>7c277982-d863-4a1c-af04-de005874b628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡PokeApp!'])[1]/following::div[4]</value>
      <webElementGuid>992acdcb-3970-4dda-b73c-1b0aea39e45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>32d2b6ed-3c51-4eae-8516-0479e7e451bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1 Bulbasaur 6.9 kg0.7 mPesoAltura' or . = '1 Bulbasaur 6.9 kg0.7 mPesoAltura')]</value>
      <webElementGuid>5696c300-dac8-45d0-8eb1-aac87011fe1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
