<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hr_Bulbasaur_card_hr</name>
   <tag></tag>
   <elementGuidId>a8c1845a-b514-4538-9551-57699dabaebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/hr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>hr</value>
      <webElementGuid>8e2635f0-3539-44d7-b9e9-46cbe94dcaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_hr</value>
      <webElementGuid>b896dcbe-672c-460f-a90a-878ed046c1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/hr[@class=&quot;card_hr&quot;]</value>
      <webElementGuid>0ccd01fa-67b1-4aeb-8983-2adbdf92c74f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/hr</value>
      <webElementGuid>62187364-0d0a-4066-a461-b9cc7dbec997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/hr</value>
      <webElementGuid>a870f53b-c2e5-40f6-9b91-9e22e056d1dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
