<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Inicio</name>
   <tag></tag>
   <elementGuidId>893b5171-a842-440a-92e4-b2647d082a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='Datos']/nav/ul/a/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fbe2009e-59bc-4083-a15b-8c7e8221ea9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2136d1e9-ad1e-4f9f-90e6-67ad2e1fa0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inicio</value>
      <webElementGuid>38c48bbc-4ceb-47a1-8212-0af861381d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Datos&quot;)/nav[1]/ul[1]/a[@class=&quot;link&quot;]/a[@class=&quot;a&quot;]</value>
      <webElementGuid>c8d3f6b7-d49a-405e-bc68-cb1e2a17abca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Datos']/nav/ul/a/a</value>
      <webElementGuid>0c3a1357-6d46-4ef5-98f9-5d9a223cb723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Inicio')]</value>
      <webElementGuid>f424b889-32a4-4afd-a9b4-518d2385060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cartful solutions'])[1]/following::a[2]</value>
      <webElementGuid>3ebc6740-f236-4851-aa08-ce1f20e292f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokedex'])[1]/following::a[2]</value>
      <webElementGuid>cffc266e-87a5-48f0-9052-18c5e78e3585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::a[1]</value>
      <webElementGuid>bb5d8c98-fafe-4cf0-825a-3dc48eada588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemons list'])[1]/preceding::a[3]</value>
      <webElementGuid>df90e6da-2b4e-4b67-a1d8-3872fdc227b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inicio']/parent::*</value>
      <webElementGuid>1d404e52-16fb-4437-afb0-2b1657646e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/a</value>
      <webElementGuid>8758d455-2c21-4999-bb07-05a6421477ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Inicio' or . = 'Inicio')]</value>
      <webElementGuid>24c96b3b-cb68-435a-8f83-3ff9833fdb27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
