<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_PokedexCartful solutionsInicioBuscar</name>
   <tag></tag>
   <elementGuidId>58d972df-0b78-4e6f-9fae-a73516f9f47d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Datos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='Datos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>a8d9eaf6-209a-4c8e-bc2c-d45f5c1b8c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Datos</value>
      <webElementGuid>bf324097-3dc5-4db4-96c5-66add97ebb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PokedexCartful solutionsInicioBuscar</value>
      <webElementGuid>a359504c-a8f9-4ffd-85bd-cf5bafd9a5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Datos&quot;)</value>
      <webElementGuid>1365cdb5-c0d3-4418-94a1-1c2c2c0984ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//header[@id='Datos']</value>
      <webElementGuid>1be641fc-d8a4-49ee-a749-ca84d7f933ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header</value>
      <webElementGuid>8c555e74-8fe6-42d5-8d31-9321f444ee87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>fdd7970f-559e-403e-ac27-90df32d550c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[@id = 'Datos' and (text() = 'PokedexCartful solutionsInicioBuscar' or . = 'PokedexCartful solutionsInicioBuscar')]</value>
      <webElementGuid>22f88c62-d581-46bf-a98d-42eb153e45fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
