<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pokedex</name>
   <tag></tag>
   <elementGuidId>a63340c9-4a7f-421c-a36d-af3ddbf88457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.nombre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Datos-personal']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8fa8398-322a-452c-81d6-9a697221b516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nombre</value>
      <webElementGuid>eed26dc2-bf78-4a4d-b287-08a67c3b9179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pokedex</value>
      <webElementGuid>a1cab94d-3462-446b-a123-4f92c97a1007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Datos-personal&quot;)/span[@class=&quot;nombre&quot;]</value>
      <webElementGuid>9ef3558a-932f-47f7-9173-f58af4c6ea5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Datos-personal']/span</value>
      <webElementGuid>4f1874cd-4530-4c19-a8d3-42ca04142f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cartful solutions'])[1]/preceding::span[1]</value>
      <webElementGuid>f408ddf0-fd71-46e7-8209-bb953f664c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/preceding::span[2]</value>
      <webElementGuid>120f9609-7384-4298-addb-65b1c5587ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pokedex']/parent::*</value>
      <webElementGuid>82cc7047-d414-41f9-9214-813fa1a5942d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>3d3e0b7a-985e-4825-abca-1c608625ab98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pokedex' or . = 'Pokedex')]</value>
      <webElementGuid>5cadc7a0-fd3f-4cd2-b7b1-6dc29f87000e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
