<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e37bebef-b030-4774-96d7-c792d86ab0a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5be6a54-47c6-4736-872c-3720a7f5e8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rickandmortyapi.com/api/character/avatar/43.jpeg</value>
      <webElementGuid>81b51d0f-e31e-4380-837b-dcfce8d52bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;card&quot;]/img[1]</value>
      <webElementGuid>ad56d7d9-22d1-4a69-9526-5e2a5d2cd501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[3]/div/img</value>
      <webElementGuid>72b42cc0-36ea-47ac-84f5-3158546ab0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://rickandmortyapi.com/api/character/avatar/43.jpeg')]</value>
      <webElementGuid>f6abcb59-1836-4634-84e7-bc73cc67224d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>55ebbe09-3ff3-43af-aa16-5a08cc6c6ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rickandmortyapi.com/api/character/avatar/43.jpeg']</value>
      <webElementGuid>e00ef53c-5148-412a-b3e2-416f40e6b24c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
