<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Peso60Habilidadesstaticlightning-rodTip_bb6020</name>
   <tag></tag>
   <elementGuidId>9c991188-6ab1-4575-bb70-772b0e9e36a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93b6a401-4ce8-48e8-8662-c5a0d3fe9404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>7a6a6852-aa36-4fec-9853-43842b8a03d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Peso60Habilidades:staticlightning-rodTiposelectricJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2</value>
      <webElementGuid>d9b5fbf0-94c6-4c65-b7ac-61dfdfec74d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]</value>
      <webElementGuid>9e36bff1-17f6-4336-a361-a615f56da3f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]</value>
      <webElementGuid>ec7b1213-c51c-4815-8f7d-9e724c03ff30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pikachu'])[1]/following::div[1]</value>
      <webElementGuid>7dbca9d6-fc69-4a30-8fe3-96699e561ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Busca a tu Pokemon'])[1]/following::div[4]</value>
      <webElementGuid>2d74e1f2-5d13-4058-8f26-fca21ef00042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>eb5de598-4f01-472e-a8c7-15f86a9fedf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Peso60Habilidades:staticlightning-rodTiposelectricJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2' or . = 'Peso60Habilidades:staticlightning-rodTiposelectricJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2')]</value>
      <webElementGuid>2ce09e76-6a9a-4efd-92a9-d0a0421aa7f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
