<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_redblueyellowgoldsilvercrystalrubysapph_10f698</name>
   <tag></tag>
   <elementGuidId>3b4e10e6-91b6-4e52-9169-25f1c3e7bffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>581e2763-0d95-4fa3-b6af-ed3513592cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>c76ab4d8-21ee-42a2-9156-7ed82f3a5ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>redblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2</value>
      <webElementGuid>ae4f2617-8218-436b-88c1-109e247c2066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;container&quot;]</value>
      <webElementGuid>00ade03a-d1f3-4c61-a072-d358c3fee9c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]</value>
      <webElementGuid>8e1c3bac-e28b-455f-a231-f74fe588fcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Juegos en los que aparece'])[1]/following::div[1]</value>
      <webElementGuid>964cb5c8-7ac3-4462-8987-a04477c90e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos'])[1]/following::div[2]</value>
      <webElementGuid>6c38cca9-2cc6-4710-b358-16bc5ac30171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>a3ea0760-f73b-4f3d-96a1-e874d32ab4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'redblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2' or . = 'redblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2')]</value>
      <webElementGuid>9cbee87d-7160-46a6-a36f-7040e08b5678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
