<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Peso300Habilidadesstaticlightning-rodTi_954028</name>
   <tag></tag>
   <elementGuidId>1885a1b1-e0a2-4f39-95b5-291227924d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>999c792f-6426-493b-9352-898ab52af884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>9f245874-13f6-46f8-9347-92f9b6705885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Peso300Habilidades:staticlightning-rodTiposelectricJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2</value>
      <webElementGuid>4e282d3a-058d-4434-96c9-944e14851a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]</value>
      <webElementGuid>f353dfa3-e460-4cfc-ac46-3f047f505341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]</value>
      <webElementGuid>96ed96c8-0549-4cb4-8524-18c69ee0ccd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raichu'])[1]/following::div[1]</value>
      <webElementGuid>7eff645d-3f24-4bf4-9968-8e34b6b9a2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Busca a tu Pokemon'])[1]/following::div[4]</value>
      <webElementGuid>7abcc361-abb5-4a45-8a27-9720dce46525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>06c9b4b5-f603-4141-b85d-cec2aa254aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Peso300Habilidades:staticlightning-rodTiposelectricJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2' or . = 'Peso300Habilidades:staticlightning-rodTiposelectricJuegos en los que apareceredblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2')]</value>
      <webElementGuid>61fbcf96-8826-406a-946c-5b283bb5d7e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
