<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Next page_card-img</name>
   <tag></tag>
   <elementGuidId>0d30a514-1fbe-43e3-ad78-0723404ac93d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00d1fbc6-19a6-415d-af3b-f542ddbcf18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png</value>
      <webElementGuid>1606bb2f-90e0-4cdb-94d8-d46e863dea13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>bulbasaur</value>
      <webElementGuid>2dcf6427-de68-4da1-8c81-7b90f197c021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img</value>
      <webElementGuid>ef1f77ac-bed8-46f8-bb98-9921b3bc8f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row rows-cols-1 row-cols-md-3 g-3 principal&quot;]/div[@class=&quot;col animate__animated animate__bounce&quot;]/div[@class=&quot;card container&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-4&quot;]/img[@class=&quot;card-img&quot;]</value>
      <webElementGuid>597e3ec4-df7c-4605-829e-c650a5591ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/img</value>
      <webElementGuid>1983683b-c75b-439a-8024-02279a9f9deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='bulbasaur']</value>
      <webElementGuid>9597cff0-1ddf-4193-9a4c-546fd6c4ea8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>dad66820-95a1-4b45-a605-3ec84527eb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png' and @alt = 'bulbasaur']</value>
      <webElementGuid>7594b614-4020-47f2-a35c-93908d1d4ef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
