<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Buscar_carousel-control-prev-icon</name>
   <tag></tag>
   <elementGuidId>209b3057-2c8b-48aa-9d8e-e1da22a29a54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.carousel-control-prev-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>817b31ef-4b1f-4bcd-bd42-e3dd9d41461b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c7e411d-40d2-4c6a-81a1-0e747abefd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-prev-icon</value>
      <webElementGuid>014e7b43-b0c3-4c1c-8413-d6e8fa65d616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row mt-5 animate__animated animate__fadeInLeft&quot;]/div[@class=&quot;col-4&quot;]/div[@class=&quot;carousel slide&quot;]/a[@class=&quot;carousel-control-prev&quot;]/span[@class=&quot;carousel-control-prev-icon&quot;]</value>
      <webElementGuid>1b8545ec-82e7-412d-a119-117286165703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/a/span</value>
      <webElementGuid>99cf3d47-ee56-489c-96d9-da4a9e6393be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>0853b474-a497-437f-819f-c2d331471883</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
