<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_bulbasaurHabilidadesovergrowchlorophyll_4c5537</name>
   <tag></tag>
   <elementGuidId>593a5506-1585-4d09-aec0-52a9a32e34b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.car-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e099f12-9f85-4ac9-967c-691f190eac42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>car-body</value>
      <webElementGuid>363a995d-fb7d-4e52-9146-876441171a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bulbasaurHabilidades:overgrowchlorophyllRead more</value>
      <webElementGuid>b14ca176-ad5d-4c6c-ac1c-fe49287f99b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row rows-cols-1 row-cols-md-3 g-3 principal&quot;]/div[@class=&quot;col animate__animated animate__bounce&quot;]/div[@class=&quot;card container&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;car-body&quot;]</value>
      <webElementGuid>e3591259-be0e-4b3d-9843-22dafc8e893c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>0a5a7538-ab36-4fca-a4d2-f3c277a9576d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next page'])[1]/following::div[7]</value>
      <webElementGuid>609dd137-71cd-4f96-b86c-34324447c1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemons list'])[1]/following::div[8]</value>
      <webElementGuid>b01450fb-6fe7-4dc9-b055-3820a8dd97c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>60461a7f-fa7c-42b6-a601-ff6d6ee3e73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'bulbasaurHabilidades:overgrowchlorophyllRead more' or . = 'bulbasaurHabilidades:overgrowchlorophyllRead more')]</value>
      <webElementGuid>7121e45f-3058-4eda-860d-6536e6ebeaa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
