<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Movimientos pound, double-slap, mega-pun_63dd36</name>
   <tag></tag>
   <elementGuidId>5c8b867c-3888-41af-9a64-d1549f6df3f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>85fef3d9-c9f5-4085-b803-f0e7638b277e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item</value>
      <webElementGuid>8720f923-7c07-46c6-90dc-d527f3d1822f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Movimientos: pound, double-slap, mega-punch, fire-punch, ice-punch, thunder-punch, mega-kick, headbutt, body-slam, take-down, double-edge, growl, sing, flamethrower, water-gun, ice-beam, blizzard, bubble-beam, submission, counter, seismic-toss, strength, solar-beam, thunderbolt, thunder-wave, thunder, dig, toxic, psychic, rage, teleport, mimic, double-team, minimize, defense-curl, light-screen, reflect, bide, metronome, fire-blast, skull-bash, amnesia, soft-boiled, dream-eater, flash, psywave, splash, rest, tri-attack, substitute, nightmare, snore, curse, protect, sweet-kiss, mud-slap, zap-cannon, icy-wind, detect, endure, charm, rollout, swagger, attract, sleep-talk, heal-bell, return, frustration, safeguard, dynamic-punch, baton-pass, encore, iron-tail, moonlight, hidden-power, rain-dance, sunny-day, psych-up, shadow-ball, rock-smash, uproar, facade, focus-punch, follow-me, helping-hand, trick, role-play, magic-coat, recycle, brick-break, knock-off, endeavor, imprison, snatch, secret-power, hyper-voice, meteor-mash, fake-tears, cosmic-power, signal-beam, bounce, covet, magical-leaf, calm-mind, shock-wave, water-pulse, gravity, wake-up-slap, healing-wish, natural-gift, fling, lucky-chant, copycat, last-resort, drain-punch, zen-headbutt, captivate, stealth-rock, grass-knot, charge-beam, wonder-room, psyshock, telekinesis, after-you, round, echoed-voice, stored-power, ally-switch, incinerate, retaliate, bestow, work-up, disarming-voice, draining-kiss, misty-terrain, play-rough, moonblast, confide, mystical-fire, dazzling-gleam, power-up-punch, spotlight, life-dew, meteor-beam, misty-explosion, dual-wingbeat, </value>
      <webElementGuid>7fdbc30e-14c4-4b95-9c79-c23be84f1e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row mt-5 animate__animated animate__fadeInLeft&quot;]/div[@class=&quot;col-8&quot;]/ul[@class=&quot;list-group list-group-flush&quot;]/li[@class=&quot;list-group-item&quot;]</value>
      <webElementGuid>6200de3f-039c-4bd6-a772-19cccb386eba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/ul/li[3]</value>
      <webElementGuid>d64c550b-91f4-44e9-91c8-089c736e3092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilidades:'])[1]/following::li[1]</value>
      <webElementGuid>01858e13-5c1e-4c20-b64c-38f494545d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::li[1]</value>
      <webElementGuid>3d5f5ace-9c1b-4894-810d-7798ddfda3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pound']/parent::*</value>
      <webElementGuid>52bd84e6-bb2f-4931-8f1c-909387770632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>c9d380cc-bf3a-49b3-ad08-e360cb16e7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Movimientos: pound, double-slap, mega-punch, fire-punch, ice-punch, thunder-punch, mega-kick, headbutt, body-slam, take-down, double-edge, growl, sing, flamethrower, water-gun, ice-beam, blizzard, bubble-beam, submission, counter, seismic-toss, strength, solar-beam, thunderbolt, thunder-wave, thunder, dig, toxic, psychic, rage, teleport, mimic, double-team, minimize, defense-curl, light-screen, reflect, bide, metronome, fire-blast, skull-bash, amnesia, soft-boiled, dream-eater, flash, psywave, splash, rest, tri-attack, substitute, nightmare, snore, curse, protect, sweet-kiss, mud-slap, zap-cannon, icy-wind, detect, endure, charm, rollout, swagger, attract, sleep-talk, heal-bell, return, frustration, safeguard, dynamic-punch, baton-pass, encore, iron-tail, moonlight, hidden-power, rain-dance, sunny-day, psych-up, shadow-ball, rock-smash, uproar, facade, focus-punch, follow-me, helping-hand, trick, role-play, magic-coat, recycle, brick-break, knock-off, endeavor, imprison, snatch, secret-power, hyper-voice, meteor-mash, fake-tears, cosmic-power, signal-beam, bounce, covet, magical-leaf, calm-mind, shock-wave, water-pulse, gravity, wake-up-slap, healing-wish, natural-gift, fling, lucky-chant, copycat, last-resort, drain-punch, zen-headbutt, captivate, stealth-rock, grass-knot, charge-beam, wonder-room, psyshock, telekinesis, after-you, round, echoed-voice, stored-power, ally-switch, incinerate, retaliate, bestow, work-up, disarming-voice, draining-kiss, misty-terrain, play-rough, moonblast, confide, mystical-fire, dazzling-gleam, power-up-punch, spotlight, life-dew, meteor-beam, misty-explosion, dual-wingbeat, ' or . = 'Movimientos: pound, double-slap, mega-punch, fire-punch, ice-punch, thunder-punch, mega-kick, headbutt, body-slam, take-down, double-edge, growl, sing, flamethrower, water-gun, ice-beam, blizzard, bubble-beam, submission, counter, seismic-toss, strength, solar-beam, thunderbolt, thunder-wave, thunder, dig, toxic, psychic, rage, teleport, mimic, double-team, minimize, defense-curl, light-screen, reflect, bide, metronome, fire-blast, skull-bash, amnesia, soft-boiled, dream-eater, flash, psywave, splash, rest, tri-attack, substitute, nightmare, snore, curse, protect, sweet-kiss, mud-slap, zap-cannon, icy-wind, detect, endure, charm, rollout, swagger, attract, sleep-talk, heal-bell, return, frustration, safeguard, dynamic-punch, baton-pass, encore, iron-tail, moonlight, hidden-power, rain-dance, sunny-day, psych-up, shadow-ball, rock-smash, uproar, facade, focus-punch, follow-me, helping-hand, trick, role-play, magic-coat, recycle, brick-break, knock-off, endeavor, imprison, snatch, secret-power, hyper-voice, meteor-mash, fake-tears, cosmic-power, signal-beam, bounce, covet, magical-leaf, calm-mind, shock-wave, water-pulse, gravity, wake-up-slap, healing-wish, natural-gift, fling, lucky-chant, copycat, last-resort, drain-punch, zen-headbutt, captivate, stealth-rock, grass-knot, charge-beam, wonder-room, psyshock, telekinesis, after-you, round, echoed-voice, stored-power, ally-switch, incinerate, retaliate, bestow, work-up, disarming-voice, draining-kiss, misty-terrain, play-rough, moonblast, confide, mystical-fire, dazzling-gleam, power-up-punch, spotlight, life-dew, meteor-beam, misty-explosion, dual-wingbeat, ')]</value>
      <webElementGuid>a41abfda-c876-43c0-8df9-69c0a7be4579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
