<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>01851ca3-e965-4c7c-a913-608ef2e948cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/header/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aa6d9f43-f994-43d2-bc2b-de647f253b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-icons-png.flaticon.com/512/528/528101.png</value>
      <webElementGuid>9408b44a-d437-4b42-9351-a4a93b13ef5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>55px</value>
      <webElementGuid>f047b5b1-48b3-4ae1-ba07-c023436d8d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;navbar&quot;]/a[@class=&quot;logo&quot;]/img[1]</value>
      <webElementGuid>ee9f3544-43f3-428b-b6e3-1176bf3c21be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/a/img</value>
      <webElementGuid>d0a33379-e931-42d8-a450-4e6c1f54ea87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-icons-png.flaticon.com/512/528/528101.png')]</value>
      <webElementGuid>0af4b622-55f5-4712-87c4-7948153c8bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>081fd928-06ac-4b87-88d5-b7b3e761d4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-icons-png.flaticon.com/512/528/528101.png']</value>
      <webElementGuid>53b4f4e6-d08d-4c03-a9b5-15faa9ded2f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
