<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Previous Pokemons</name>
   <tag></tag>
   <elementGuidId>17b10e31-ba09-4887-9f0f-c2443882cf10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[10]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37edc509-5baa-4f15-8773-cd7aa3213db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__cta</value>
      <webElementGuid>d797cca1-a607-4853-8080-c6b4a4d7f1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡Previous Pokemons!</value>
      <webElementGuid>f439bc15-4d8d-4cb9-a97d-a1f1b215f311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;buttons&quot;]/button[@class=&quot;card__cta&quot;]</value>
      <webElementGuid>b1d42d9e-8bad-4d1f-a86e-298c3dc6c2ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[10]/button[2]</value>
      <webElementGuid>b04a9086-5bfb-4c68-af3c-b7fde0441996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Next Pokemons!'])[1]/following::button[1]</value>
      <webElementGuid>4bd188fc-e7a1-4a6f-839b-0d427f6b7549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Altura'])[8]/following::button[2]</value>
      <webElementGuid>eac67154-198f-40bd-b7b0-e61370e31411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡Previous Pokemons!']/parent::*</value>
      <webElementGuid>c9986a75-e7f9-4f57-9a24-71ce81813075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>840447e6-613b-4409-b24d-96c23f15d82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '¡Previous Pokemons!' or . = '¡Previous Pokemons!')]</value>
      <webElementGuid>53ca17de-04cd-424a-bc22-260d1a1ec1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
