<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next Pokemons</name>
   <tag></tag>
   <elementGuidId>3e681f87-59f2-482b-8f82-3a8a94b9e2bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.card__cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[10]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b784a7d-97a0-4b91-9dc2-24d00c8b78e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__cta</value>
      <webElementGuid>917d0793-412c-41f3-aa1c-d7296e645b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡Next Pokemons!</value>
      <webElementGuid>25ed8412-0c45-47bd-b1f2-be7dcfad32ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;buttons&quot;]/button[@class=&quot;card__cta&quot;]</value>
      <webElementGuid>fed4d144-f37f-41f7-9cd4-5d44e1f976d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[10]/button</value>
      <webElementGuid>9c9ab6fb-3c41-48cd-96e2-08faaf5a9aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Altura'])[8]/following::button[1]</value>
      <webElementGuid>ef064374-5801-4b7d-9a7c-ba1de821f925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[8]/following::button[1]</value>
      <webElementGuid>8ae36809-1b33-46ac-9fb7-d33db0218f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡Next Pokemons!']/parent::*</value>
      <webElementGuid>21137cb1-b5fb-413b-b9b0-554ac3680cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>189acf5c-3bf6-463f-b646-879192745894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '¡Next Pokemons!' or . = '¡Next Pokemons!')]</value>
      <webElementGuid>65373604-2aec-4cd0-8383-7c33b4cc01c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
