<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_6  charizardHabilidadesblazesolar-power</name>
   <tag></tag>
   <elementGuidId>ad34bbb1-3434-4bb6-8f7f-a65f6963ce21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card__items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71c528f7-6858-4690-88d8-07639357f39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__items</value>
      <webElementGuid>4f5a07fb-b88c-44e2-aacf-dd45aaabcc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6  charizardHabilidadesblazesolar-power</value>
      <webElementGuid>0b234055-dc76-4ad2-9b01-7e96824e7555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]</value>
      <webElementGuid>d721931f-73f4-4ee5-bc5b-e4fe1e03c659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>c8b3dadc-2633-425a-874b-28976e5b7887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡PokeApp!'])[1]/following::div[1]</value>
      <webElementGuid>d3784a41-2c19-4536-b9df-45abfd673709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>436dab74-4c40-4421-93be-e66aa2fc7dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '6  charizardHabilidadesblazesolar-power' or . = '6  charizardHabilidadesblazesolar-power')]</value>
      <webElementGuid>093b2817-1dbf-4b0a-b941-2a0d2211fe68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
