<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_6</name>
   <tag></tag>
   <elementGuidId>9ebfe33e-7a89-4fec-b5be-5a57df330f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.card__id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>97af352d-96d7-4b88-bb8d-824c89a80b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__id</value>
      <webElementGuid>2f16c598-7221-42f9-94b4-d55e6600ba5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f8e6a22e-1fcc-435e-8951-5a1bdd3df25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[@class=&quot;card__division&quot;]/h1[@class=&quot;card__id&quot;]</value>
      <webElementGuid>96cb7e41-b8f9-47e5-a899-e0981b00604e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/h1</value>
      <webElementGuid>5dff8b97-50b2-4a8c-930d-cdfc36667ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡PokeApp!'])[1]/following::h1[1]</value>
      <webElementGuid>563b4353-3b80-44df-b6be-f6e46bc8f118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6']/parent::*</value>
      <webElementGuid>24536314-6728-4075-adc6-3c0672929203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/h1</value>
      <webElementGuid>a1633887-45f3-4c62-8ea4-d60ee42f7b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '6' or . = '6')]</value>
      <webElementGuid>a0bc930a-5b4f-40ee-ba01-40c71b51911d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
