<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Peso</name>
   <tag></tag>
   <elementGuidId>922d2b37-b7cd-45bc-b600-a91df44d4386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.card_data.text1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cf465602-676f-4270-bba3-644851bc4d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_data text1</value>
      <webElementGuid>beb6eafd-d424-49e6-a979-329711fe8a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Peso</value>
      <webElementGuid>4cca0e73-2e9b-41a5-be4f-e690b9c96fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/div[1]/h2[@class=&quot;card_data text1&quot;]</value>
      <webElementGuid>37d91c95-c39c-4e51-905d-cf43e49692b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/h2</value>
      <webElementGuid>aea90809-fb5d-4b78-9f95-9bed4b678e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilidades'])[1]/following::h2[1]</value>
      <webElementGuid>3f72c004-a9a1-41d9-8794-59d1bcdf80d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Altura'])[1]/preceding::h2[1]</value>
      <webElementGuid>886acac6-5b8b-439a-91af-8e48968fb2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Peso']/parent::*</value>
      <webElementGuid>87249f60-1ba2-4350-a7e2-966d0e8fa5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>156c661c-650e-4e3c-9e0a-42f1b37b5d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Peso' or . = 'Peso')]</value>
      <webElementGuid>42701b1e-9be9-46c6-a818-b5cc01c69307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
