<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_solar-power</name>
   <tag></tag>
   <elementGuidId>c114a94e-ff33-4c93-9b92-9d985dbe8cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/h2/p/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c7142feb-e658-4e31-9f5f-cd9e0d2681c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_data ability</value>
      <webElementGuid>407685f8-b404-47d2-8c66-e1d9e93bf61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>solar-power</value>
      <webElementGuid>aca9e432-423f-48da-a445-ccb81c67980d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/h2[@class=&quot;card_data text3&quot;]/p[1]/p[@class=&quot;card_data ability&quot;]</value>
      <webElementGuid>4769e77f-00f3-43f7-b613-893e4fc98c6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/h2/p/p[2]</value>
      <webElementGuid>98cb0d17-a134-492e-9f08-66410d7def46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/preceding::p[3]</value>
      <webElementGuid>8d6d5701-f9d0-497f-b3b3-bfb3c2632e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='solar-power']/parent::*</value>
      <webElementGuid>15e86a0f-aa6d-4d1d-9021-94126781d021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>3efdae69-48a0-4704-a2e8-249f0c550033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'solar-power' or . = 'solar-power')]</value>
      <webElementGuid>2ab307e0-47c4-40f4-8639-3f734dbfb773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
