<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_static</name>
   <tag></tag>
   <elementGuidId>fa2e503f-7bdb-4c47-8d96-966e508cebb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.card_data.ability</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/h2/p/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fabbf728-eff6-4dbf-b802-5435addfe0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_data ability</value>
      <webElementGuid>3f438c33-e128-4e0c-a398-4235b100eedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>b5ee96a4-32ac-4578-84d6-582804013dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/h2[@class=&quot;card_data text3&quot;]/p[1]/p[@class=&quot;card_data ability&quot;]</value>
      <webElementGuid>ab02acbd-13b8-4d73-93e4-931b0f339d7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/h2/p/p</value>
      <webElementGuid>7cc5561a-6ee7-405f-9c3d-34b2dc1142fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/preceding::p[4]</value>
      <webElementGuid>a95aa7dd-8a8d-4a76-8b6a-d9556a184c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='static']/parent::*</value>
      <webElementGuid>c44ece52-398a-4157-bff8-8fe34a0cdd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/p</value>
      <webElementGuid>b0cbf013-d4eb-472d-9ff4-13c2113c4362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'static' or . = 'static')]</value>
      <webElementGuid>05e6a891-2a79-4541-82a4-efbd05bb7af4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
