<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_20raticate</name>
   <tag></tag>
   <elementGuidId>0356e54c-74a8-4290-98e1-e8aa5a136ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/div[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>787a3ac0-47a2-4981-87b6-33f0951a2c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__container</value>
      <webElementGuid>79b3db5b-c091-41e0-9fbd-23f82b9bb849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20raticate</value>
      <webElementGuid>fb4ffaf8-e2e4-4f89-b2c8-aa81035b0f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;container&quot;]/div[@class=&quot;card__info&quot;]/div[@class=&quot;card__container&quot;]</value>
      <webElementGuid>c31a42bc-446c-4d50-b77f-c9e2c3c56b45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div[20]</value>
      <webElementGuid>62154ef2-560a-4975-a24e-d782f57e9d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rattata'])[1]/following::div[1]</value>
      <webElementGuid>3b0f82f3-b2bd-4ae3-8219-25f735d28f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pidgeot'])[1]/following::div[2]</value>
      <webElementGuid>6507c17b-5bf7-4059-b0b8-cb041a0d97b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]</value>
      <webElementGuid>5e9a061e-d1e7-401d-8a6b-f267f29744bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '20raticate' or . = '20raticate')]</value>
      <webElementGuid>8849fd1d-15dd-4e1f-b6b0-68916b9b2de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
