<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_bulbasaur</name>
   <tag></tag>
   <elementGuidId>4d942f66-0a2a-401f-afc3-64005db1f00c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.names</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>94c57e76-93ab-42aa-98a6-03b9998135aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>names</value>
      <webElementGuid>e1162f8c-9934-4cda-b350-46d7376264a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bulbasaur</value>
      <webElementGuid>35a1e33e-cd3d-4c1c-a329-5222b8667f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/h2[@class=&quot;names&quot;]</value>
      <webElementGuid>ab05dddc-fdd5-449b-8678-ddea4a58150e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/h2</value>
      <webElementGuid>f927a3fe-548d-4705-aa4e-7c1f4a63484e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::h2[1]</value>
      <webElementGuid>eb8fb2d0-bba7-4e3a-9bd2-a1328ad0c170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raticate'])[1]/following::h2[1]</value>
      <webElementGuid>433e4d09-b9f9-4972-819f-698e51173015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='overgrow'])[1]/preceding::h2[1]</value>
      <webElementGuid>5f124ea2-f89c-466f-ab28-30691324781e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chlorophyll'])[1]/preceding::h2[2]</value>
      <webElementGuid>5529a7fa-fdf6-4293-a3a1-a9a100eb2dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h2</value>
      <webElementGuid>a58af48b-0644-4b7b-a8c7-cec0356abd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'bulbasaur' or . = 'bulbasaur')]</value>
      <webElementGuid>ff82ace6-04f5-4871-9d26-c53e6f48d786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
