<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ivysaur_img</name>
   <tag></tag>
   <elementGuidId>68d091c4-91f4-4653-a059-be074911978c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show1']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1350942b-13f2-41c0-b6b1-b73a7ada44ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg</value>
      <webElementGuid>8310439b-8bf2-4d1c-b3f1-64882a6d9db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pokemon__img</value>
      <webElementGuid>d125926f-12b9-49a0-8136-c207004bb5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d564a611-af53-40db-a936-e6ac80fdfe50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show1&quot;)/div[@class=&quot;show__container&quot;]/img[@class=&quot;img&quot;]</value>
      <webElementGuid>a570fb0c-49b4-4d81-9daa-3abfc9dffda3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show1']/div/img</value>
      <webElementGuid>92b6ac86-1c52-4efa-a3d7-c0808794f2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='pokemon__img']</value>
      <webElementGuid>d73c70e2-433e-453c-80b4-aef4d486e03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>159edf98-f35f-4b1b-837b-b36edbb2b87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg' and @alt = 'pokemon__img']</value>
      <webElementGuid>9793cfa9-bbc0-44a6-b019-507ad811d0ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
