<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_redblueyellowgoldsilvercrystalrubysapph_10f698</name>
   <tag></tag>
   <elementGuidId>8a190951-5ca1-42fd-979b-0fab99294095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50a96daa-342c-419f-900b-3a1586fdaa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>5e7145d7-6bce-46a3-a6d7-b8f1bef61b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>redblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2</value>
      <webElementGuid>5f9a47f8-03ed-4e06-9c33-046278025f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;container&quot;]</value>
      <webElementGuid>28ace1ec-639c-4c05-807f-e997dc7a25a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]</value>
      <webElementGuid>d25a2490-c9cc-484d-9444-c0c5a9e61fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Juegos en los que aparece'])[1]/following::div[1]</value>
      <webElementGuid>a7fc78ad-f9c1-43ed-bddf-ae28bce9d887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos'])[1]/following::div[2]</value>
      <webElementGuid>277df361-72e9-4a71-af08-3f339c6f339e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>e3975794-b658-4143-8dff-c1b79965c63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'redblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2' or . = 'redblueyellowgoldsilvercrystalrubysapphireemeraldfireredleafgreendiamondpearlplatinumheartgoldsoulsilverblackwhiteblack-2white-2')]</value>
      <webElementGuid>4af90b38-c610-4328-beb5-45a8629cdb96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
