<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>dcfc2e06-167b-4f70-a864-19dc4a378b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/table/tbody/tr[2]/td[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cbc33abb-0a90-4bf2-9805-c120578b52de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png</value>
      <webElementGuid>1a72da32-9519-4704-bc46-1169d14f51fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/table[1]/tbody[@class=&quot;container&quot;]/tr[@class=&quot;card2&quot;]/td[3]/img[1]</value>
      <webElementGuid>ba291358-1beb-46ae-a48d-d45a8cea2807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/table/tbody/tr[2]/td[3]/img</value>
      <webElementGuid>16a62b5d-1cb0-4245-b36e-d1087a4c9fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png')]</value>
      <webElementGuid>65d3c2ab-4f72-4b20-a81e-8e7b19464c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/img</value>
      <webElementGuid>322cab5a-4173-48cc-9041-603aff387834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png']</value>
      <webElementGuid>9b694afe-a847-4039-b7fc-5ee26f6c4b21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
