<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ID 2</name>
   <tag></tag>
   <elementGuidId>6365c1f7-cfb9-4711-800a-0e13cf546d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/table/tbody/tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>42963fe1-fa45-4431-b3a9-7f57c06d1742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>d3eb71a7-93c8-49ff-ad56-b611faa8ba51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID: 2 </value>
      <webElementGuid>204cd2b1-1aae-4695-8184-8713c44b7e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/table[1]/tbody[@class=&quot;container&quot;]/tr[@class=&quot;card2&quot;]/td[@class=&quot;container&quot;]</value>
      <webElementGuid>e51bbd40-cbdd-48ee-a488-293f39f20d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/table/tbody/tr[2]/td</value>
      <webElementGuid>09a94817-15f2-48a7-8e17-316a6023cfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>67fbe1f1-7db5-4ed0-8573-d0ed78104477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'ID: 2 ' or . = 'ID: 2 ')]</value>
      <webElementGuid>804f1a37-0544-45d6-a2c2-421d1adcd57f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
