<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_26  raichuHabilidadesstaticlightning-rod</name>
   <tag></tag>
   <elementGuidId>28dedb77-9280-48c8-81ec-c426a663e813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card__items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4fadf60-586f-40ca-a02c-bf3fb63e59c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__items</value>
      <webElementGuid>8e896205-e4a2-4aae-8213-d684bbbb884d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26  raichuHabilidadesstaticlightning-rod</value>
      <webElementGuid>9b0962d8-58ae-4206-a765-dfc424e84f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]</value>
      <webElementGuid>794dd0a1-5a53-4a7c-818b-a75be09c8a1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>0c3e614a-f45a-4383-ae73-84e4b10d3bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡PokeApp!'])[1]/following::div[1]</value>
      <webElementGuid>bb9a9c16-0e19-498d-9f7f-40a607086b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>3a6aba54-3553-419b-8dd1-1969433450f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '26  raichuHabilidadesstaticlightning-rod' or . = '26  raichuHabilidadesstaticlightning-rod')]</value>
      <webElementGuid>415cbb47-18e4-467f-a34a-089808f52fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
