<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_5  charmeleonHabilidadesblazesolar-power</name>
   <tag></tag>
   <elementGuidId>ca97cbae-7a96-4b89-9985-4f72134cbcbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card__items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b637be08-5e34-488d-b8f2-455210765e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__items</value>
      <webElementGuid>60a20823-9609-495f-b9bb-801e3ce5db91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5  charmeleonHabilidadesblazesolar-power</value>
      <webElementGuid>a0aa4d11-ccc1-405d-998a-a0521eb2d1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]</value>
      <webElementGuid>e27419e0-ca6b-4504-8784-3e3585a60f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>cd47d2cf-aa7b-4bb7-ae0c-1217462ca3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡PokeApp!'])[1]/following::div[1]</value>
      <webElementGuid>7bd9f6a2-6bb1-4302-b6ee-3095f7b0fc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>1eb7de35-f928-4c72-ad19-c4947352a2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '5  charmeleonHabilidadesblazesolar-power' or . = '5  charmeleonHabilidadesblazesolar-power')]</value>
      <webElementGuid>2077c5f2-cf59-4180-9286-814ad94fe8e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
