<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_charmeleon</name>
   <tag></tag>
   <elementGuidId>fcbbee4d-840d-42fe-a36e-2645a9152d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.card__name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d5f284d1-c356-4ee7-b430-289b3726b499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__name</value>
      <webElementGuid>ff6a7b34-1064-4ca0-8bc9-3517f0c439c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  charmeleon</value>
      <webElementGuid>c241461d-37a4-43ee-a64a-28c58ab68d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/h1[@class=&quot;card__name&quot;]</value>
      <webElementGuid>374c2dc4-03a1-4996-9f0b-903084b280ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/h1</value>
      <webElementGuid>7c6800e6-c6e4-44a7-840e-567b04180504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡PokeApp!'])[1]/following::h1[2]</value>
      <webElementGuid>420b5bec-b39e-4b12-85c8-831006e17e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='charmeleon']/parent::*</value>
      <webElementGuid>083d2206-887b-4729-b718-a387a46f0083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h1</value>
      <webElementGuid>4b39fd93-10e7-4b21-a4fa-ef74bc035b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '  charmeleon' or . = '  charmeleon')]</value>
      <webElementGuid>c1ad86a3-7d83-43ce-9e7c-6008b2c3d477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
