<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Habilidadesstaticlightning-rod</name>
   <tag></tag>
   <elementGuidId>a8260963-c451-430a-9fbf-a1836c49c05a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.card_data.text3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2e35cdc2-05ac-4d62-9387-f3f7335bc665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_data text3</value>
      <webElementGuid>f0881845-fa82-4ed4-9208-c1481d7d3bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Habilidadesstaticlightning-rod</value>
      <webElementGuid>1586b423-4b4e-4043-a770-cc6fa2d3f92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/h2[@class=&quot;card_data text3&quot;]</value>
      <webElementGuid>f89fd359-d420-4bc7-90a8-e887b03d33a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/h2</value>
      <webElementGuid>ce58b8cb-ff8e-4293-82ab-76785c42025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡PokeApp!'])[1]/following::h2[1]</value>
      <webElementGuid>2af5d014-2c66-44fb-a3c0-49dd21435fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/preceding::h2[1]</value>
      <webElementGuid>a0927726-1237-4b9e-9f65-7bc69fc88d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Habilidades']/parent::*</value>
      <webElementGuid>2aa31d4e-0d67-498a-b10f-695212b30e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>842348fe-50e5-4b3f-befe-ee03a8821d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Habilidadesstaticlightning-rod' or . = 'Habilidadesstaticlightning-rod')]</value>
      <webElementGuid>e0db4758-637a-40c9-bc66-5a9462df20d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
