<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PokeApp_card__img_1</name>
   <tag></tag>
   <elementGuidId>a3f78992-8275-4ac5-8e71-d67f2e56e8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card__img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7f9dd436-137f-4d75-a3c1-1a5c70681b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card__img</value>
      <webElementGuid>a16cede6-081e-436e-9c30-cf3257afc482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png</value>
      <webElementGuid>8e975c6e-9af0-429a-9bb6-6732aaa0e142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[@class=&quot;card__division&quot;]/img[@class=&quot;card__img&quot;]</value>
      <webElementGuid>103b8d6e-1bf1-4a88-983c-d849e258c676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/img</value>
      <webElementGuid>b0d52af7-842d-4b14-82c4-73960af4e47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png')]</value>
      <webElementGuid>c3919257-b6e4-4e57-b008-ad245c41af88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a6284ef5-0f91-4735-8bd4-a7e255e0a56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png']</value>
      <webElementGuid>1992ff57-6fa1-4e84-ba33-da77a2c0bc3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
