<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_blaze</name>
   <tag></tag>
   <elementGuidId>a770ca8c-a139-49a7-b85f-fa39940d2c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.card_data.ability</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/h2/p/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>96d33ba2-eeb8-4ec3-8342-4a495db90b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_data ability</value>
      <webElementGuid>6bbc78b6-19cc-4dc6-a12b-6d102b7329d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>blaze</value>
      <webElementGuid>d4fa9120-84a7-45c2-86b9-d1ea0ea53cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/h2[@class=&quot;card_data text3&quot;]/p[1]/p[@class=&quot;card_data ability&quot;]</value>
      <webElementGuid>69a29f50-03f4-42a1-9888-a0bd8ef5847e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/h2/p/p</value>
      <webElementGuid>7fb8fe3a-896e-40fe-8a7c-463ba2d24589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/preceding::p[4]</value>
      <webElementGuid>eb35b590-3efb-4eca-9990-b656b0d44eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='blaze']/parent::*</value>
      <webElementGuid>97e089d8-46b8-4bc1-bf54-71d22a9f53fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/p</value>
      <webElementGuid>9da863c4-d2c9-4914-8bc0-42b6724ecb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'blaze' or . = 'blaze')]</value>
      <webElementGuid>8a6d20d1-871c-45b6-8ed1-124ea62d703e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
