<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_lightning-rod</name>
   <tag></tag>
   <elementGuidId>4804ce22-7440-4e36-861e-8408887ea6bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/h2/p/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2f10618a-d01c-49e1-9128-d713536bfc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_data ability</value>
      <webElementGuid>998f6337-5a1b-4d9c-a8e3-a3971be5e731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>lightning-rod</value>
      <webElementGuid>ee3182c8-ff13-4663-aa2d-2599e785bec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;card__items&quot;]/div[2]/h2[@class=&quot;card_data text3&quot;]/p[1]/p[@class=&quot;card_data ability&quot;]</value>
      <webElementGuid>ecb8e0c2-6d2d-4763-879d-0e4fda7dcf35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/h2/p/p[2]</value>
      <webElementGuid>b4c8c1ce-f49b-427d-9a66-2d5cf5ffba8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/preceding::p[3]</value>
      <webElementGuid>8fe5dbc5-b5f1-4bef-85e6-4f847971db58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='lightning-rod']/parent::*</value>
      <webElementGuid>27ed27a7-602a-4a9e-899c-35daaf23563c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>5fb87ec1-fa09-41db-9711-fd0de70f6411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'lightning-rod' or . = 'lightning-rod')]</value>
      <webElementGuid>fe83c307-b39f-4388-a7e7-85812e23c9d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
